### ISSUE TITLE
ReadOnly

### ISSUE THREAD

**Issue by Josh-McFarlin** [concludio/react-mathlive#10]
Is it possible to disable/make the field readonly? It could be a very useful option for different uses.

**Comment by Khazuar** [comment]
I already thought about that, too. I think the wrapper could "simulate" this, but this should probably be supported by mathlive directly I feel.

**Comment by Khazuar** [comment]
I created an issue with the base-library (see https://github.com/arnog/mathlive/issues/339). Once this is supported, this wrapper doesn't strictly need any update.

**Comment by Khazuar** [comment]
This has been solved in the latest version of mathlive and can be used like
```jsx
<MathFieldComponent
	latex="f(o\cdot o)"
	mathFieldConfig={{
		readOnly: true,
	}}
/>
```
