### ISSUE TITLE
how to listen keyDown event?

### ISSUE THREAD

**Issue by linlinNB** [concludio/react-mathlive#19]

**Comment by linlinNB** [comment]
how to setting Fontsize?

**Comment by Khazuar** [comment]
You can use the `mathfieldConfig`-property to provide configuration for the underlying mathfield, like this:
```tsx
<MathfieldComponent 
  initialLatex="f(x)"
  mathfieldConfig={{
    onKeystroke: (mathfield, keystroke, event) => { /* whatever */ },
    style: {
      fontSize: 15,
    },
  }}
/>
```
You can see a complete documentation of all the configuration options [here](https://cortexjs.io/docs/mathlive/)

Hope that helps.

**Comment by linlinNB** [comment]
Thank you for your answer. I find problem that ’style‘ attribute doesn't work.

**Comment by Khazuar** [comment]
That would be an issue with [mathlive](https://github.com/arnog/mathlive) then

**Comment by arnog** [comment]
The `style` attribute is not a valid MathLive option (but maybe it's a mathlive-react attribute?). With MathLive, the way you would control the size of the mathfield is by styling the element containing the mathfield (i.e. setting the CSS `font-size` attribute of that element). I think this should also work with mathlive-react, though.
